### ISSUE TITLE
Lead opening proposal doesn't indicate the minimum stake required

### ISSUE THREAD

**Issue by mochet** [Joystream/pioneer#2272] opened 2022-02-19 21:06 UTC
This text field does not detect what the minimum stake requirements for the opening actually are:
![image](https://user-images.githubusercontent.com/50830161/154819043-9c86c8fc-d0d4-4010-ab61-b214d31574d3.png)

In this instance the minimum stake requirements are `2000 JOY`:
![image](https://user-images.githubusercontent.com/50830161/154819062-6428bcb3-e596-473c-9090-5ef38c174784.png)

Previously I was able to submit an opening proposal that included a stake requirement below `2000 JOY` which resulted in a failed execution:
![image](https://user-images.githubusercontent.com/50830161/154819085-bb3fa167-528f-4df4-8885-d3580b03b12f.png)

**Comment by mochet** [comment] 2022-02-19 21:14
This also applies for the unstaking period:
![image](https://user-images.githubusercontent.com/50830161/154819269-f1ee8595-b71e-49fe-89f7-09493e6b85f5.png)

**Comment by bwhm** [comment] 2022-02-21 11:40
Hey,

This issue has already been raised, but you are correct! It's not actually a limit on the proposal inputs, but the `<workingGroup>.createOpening` extrinsic. This results in a bad UX, as users will make the proposal, the Council will approve, and no one will understand why it failed.

**Comment by dmtrjsg** [comment] 2022-02-21 15:41
Duplicate of 2280

**Closed by dmtrjsg** 2022-02-21 15:41 UTC
Labels: bug
