### ISSUE TITLE
[USERSNAP] Forums: Using reply doesn't seem to work

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4037] opened 2023-01-08 10:47 UTC
**Taken at**: https://pioneerapp.xyz/#/forum/thread/9
**Fields**:
- Houston, we have a problem.: Forums: Using reply doesn&#39;t seem to work
- Comment: In this forum thread I have replied twice: https://pioneerapp.xyz/#/forum/thread/9

both times the reply is not registered
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b3f0a6df-135d-4218-a35d-f41c73f5c923-annotated_f03efb6d-7214-418a-bb36-83fdb49be459.png?etag=30680c8f3080e9a785054fe3202a463a)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/b3f0a6df-135d-4218-a35d-f41c73f5c923-annotated_f03efb6d-7214-418a-bb36-83fdb49be459.png?etag=30680c8f3080e9a785054fe3202a463a)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1227x665
**[Open #364 in Usersnap](https://app.usersnap.com/l/feedback/d93420db-2c47-4905-aea9-4e2468142f36?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-08 11:01
duplicate of #3967
please use this deployment: https://dao-git-fork-mkbeefcake-fix-forumpostreplyntshow4022-joystream.vercel.app/

**Closed by traumschule** 2023-01-08 11:01 UTC
Labels: bug
