### ISSUE TITLE
[USERSNAP] Reply to a comment is not displayed

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4008] opened 2023-01-04 14:51 UTC
**Taken at**: https://pioneerapp.xyz/#/proposals/preview/24
**Fields**:
- Houston, we have a problem.: Reply to a comment is not displayed
- Comment: Reply to a comment is not displayed. I wrote a comment: It&#39;s okay.
Only in this proposal, the comments are all messed up. They go from the bottom to the top of the date.
- Feedback: adovrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/06103b91-37b4-4692-892f-57c43a8d190f-annotated_f0370106-0636-4428-bc44-2e3d2e92747c.png?etag=27ae3eeadce1195978a9a0eb56d76f54)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/06103b91-37b4-4692-892f-57c43a8d190f-annotated_f0370106-0636-4428-bc44-2e3d2e92747c.png?etag=27ae3eeadce1195978a9a0eb56d76f54)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**[Open #354 in Usersnap](https://app.usersnap.com/l/feedback/572d1523-31ae-4b8c-8145-d79859699ebb?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-04 19:53
duplicate of #3967

**Closed by traumschule** 2023-01-04 19:53 UTC
Labels: bug
