### ISSUE TITLE
[USERSNAP] Preview does not work

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4100] opened 2023-01-18 18:23 UTC
**Taken at**: https://pioneerapp.xyz/#/forum/category/38
**Fields**:
- Houston, we have a problem.: Preview does not work
- Comment: Expected to see posting preview

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/dc450682-6bab-41b6-9900-eaa0346c95e9-annotated_681d75da-b2e1-4db3-aaa3-35919803a545.png?etag=3a9c465714168506def0051b6392b8b6)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/dc450682-6bab-41b6-9900-eaa0346c95e9-annotated_681d75da-b2e1-4db3-aaa3-35919803a545.png?etag=3a9c465714168506def0051b6392b8b6)*

**Browser**: Chrome 109 (Windows 10)
**Screen size**: 1920x1080
**Browser size**: 1920x973
**[View screen recording](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/screen_recording/866db684-9f8e-42f2-bf8b-081539631d30_screen_recording_805ee563-fefe-4296-a973-55a57da6b01a.webm?etag=d1cb83b1c1b1abbc8a237348501f9ac2)**
**[Open #379 in Usersnap](https://app.usersnap.com/l/feedback/b9d3850c-4b00-4b7d-b716-816f0fb6c7a0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-19 07:12
duplicate of #3928

**Closed by traumschule** 2023-01-19 07:12 UTC
Labels: bug
