### ISSUE TITLE
[feature request] Support finding members by ID

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3253] opened 2022-06-16 22:20 UTC
## Scope

- [ ] Support finding members by ID

<img width="1229" alt="Screenshot 2022-06-17 at 12 54 14" src="https://user-images.githubusercontent.com/93924525/174234188-353351ec-f53b-497e-aceb-f11b2de1d660.png">

NB: pls do together with : 
- https://github.com/Joystream/pioneer/issues/2657

_____
**Taken at**: https://dao.joystream.org/#/members
**Fields**:
- Which feature are you missing?: Support finding members by ID
- What problem would that solve for you?: SSIA

**Browser**: Chrome 102 (Linux)
**Screen size**: 1920x1080
**[Open #20 in Usersnap](https://app.usersnap.com/l/feedback/9c5a8e8b-c77f-4e57-b084-a08cb0b9bf2f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2022-10-20 17:51
duplicate of #3390 #2032 (implemented)

![member search](https://user-images.githubusercontent.com/31551045/197021700-d65abd16-0244-4ad0-9d95-e305e0b1f676.png)

**Closed by traumschule** 2022-10-20 17:51 UTC
Labels: scope:members, community-dev, SP:3
