### ISSUE TITLE
[USERSNAP] tomato#9464

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2264] opened 2022-02-19 10:38 UTC
**Taken at**: https://pioneer-2.vercel.app/#/election
**Fields**:
- Discrod Handle: tomato#9464
- Give us some details: I have 5m+ JOY free but can&#39;t apply. The alice key also has 90m+
- Houston, we have a problem.: wrong balance detected
- not detecting correct balances?

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/92defdd0-0735-4d07-8bb3-39bd593b7865-annotated_cf7f2cc1-4314-4118-9678-c86f35abb99d.png?etag=0809c811b852e4f6ae3e73ea4bd8d82c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/92defdd0-0735-4d07-8bb3-39bd593b7865-annotated_cf7f2cc1-4314-4118-9678-c86f35abb99d.png?etag=0809c811b852e4f6ae3e73ea4bd8d82c)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 2395x1097
**[Open #3 in Usersnap](https://app.usersnap.com/l/feedback/2562eb26-4a82-4683-9423-3ccba96a143d?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment] 2022-02-19 20:47
This may have been caused by the query node being broken, another way this same problem was shown is detailed here: https://github.com/Joystream/pioneer/issues/2271

**Comment by bwhm** [comment] 2022-02-21 11:41
I'll close this, as it's conceptually the same as the issue you're referencing.

**Closed by bwhm** 2022-02-21 11:41 UTC
Labels: bug
