### ISSUE TITLE
Enhance election lifecycle clarity

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#4005] opened 2023-01-04 11:06 UTC
# Background

Currently, the election works like this

```
Announcing Period: 14 days
Voting Period: 3 days
Reveal Period: 3 days
Idle Period: 1 days
Total: 21 days = 3 weeks
```

However, when you land on the election screen, you jus see the current period and how much time is left. This makes it hard for people to understand the full cycle, in terms of duration and structure, and this deters participation from both prospective candidates and voters.

# Proposal

Add some sort of visual representation to this screen which solves this.

**Comment by traumschule** [comment] 2023-01-04 19:31
duplicate of #4006

**Closed by traumschule** 2023-01-04 19:31 UTC
Labels: enhancement, design
