### ISSUE TITLE
[USERSNAP] After approval of proposal the action button is "See My Proposal"

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2924] opened 2022-04-26 17:33 UTC
**Scope:**

- [ ]  Update CTA on confirmation modal to "Back to Proposals" and redirect user to proposals list on click

____________

**Taken at**: https://dao.joystream.org/#/proposals/preview/118
**Fields**:
- Houston, we have a problem.: After approval of proposal the action button is &#34;See My Proposal&#34;
- Comment: After approval of proposal the action button is &#34;See My Proposal&#34; but it should be something else instead, e.g. Back to proposal.
- Feedback: GH: oleksanderkorn DS: lkskrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5d5bdde5-a0dd-4aa6-b4d8-b56297ac1764-annotated_18ae86d1-c4d9-43c5-bdda-b46a1e0ca443.png?etag=8aeeab00eec9cfe4aabbd6c8d074224d)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/5d5bdde5-a0dd-4aa6-b4d8-b56297ac1764-annotated_18ae86d1-c4d9-43c5-bdda-b46a1e0ca443.png?etag=8aeeab00eec9cfe4aabbd6c8d074224d)*

**Browser**: Chrome 100 (macOS Catalina)
**Screen size**: 1920x1200
**Browser size**: 1920x1096
**[Open #228 in Usersnap](https://app.usersnap.com/l/feedback/350eae41-709c-4d7b-8b50-fd359f03e703?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by singulart** [comment] 2022-05-02 17:52
Assigned to @talentdev0807

**Comment by talentdev0807** [comment] 2022-05-03 11:48
This bounty was already fixed
Adding NewProposal : "See My Proposal" 
Voting : "Back to Proposals "

**Comment by singulart** [comment] 2022-05-03 11:59
Looks like a duplicate of https://github.com/Joystream/pioneer/issues/2838

**Comment by polikosi** [comment] 2022-06-11 15:02
verified on staging. Looks good:
NewProposal : "See My Proposal" and redirected to just created proposal
![Screenshot_106](https://user-images.githubusercontent.com/80429191/173193139-78bc7c44-a4e3-40ce-9f1f-e72e3f2e5e63.png)

Voting : "Back to Proposals "
![Screenshot_107](https://user-images.githubusercontent.com/80429191/173193192-100860f4-b3d9-487f-945f-e02051215797.png)
and redirected to "Prorposal>Current" page:
![Screenshot_108](https://user-images.githubusercontent.com/80429191/173193222-1187b08d-5bbb-4453-b9a6-22412c151e29.png)

**Closed** 2022-06-23 14:37 UTC
Labels: bug, ux, community-dev, qa-tested-ready-for-prod, bounty-backlog, jsg-code-review, SP:1, qa-effort-30min
