### ISSUE TITLE
Withdrawal Period - Claim Reward

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2640] opened 2022-03-23 18:03 UTC
## Context

Few fixes after testing withdrawal flow for bounties

## Scope
- [x] Unclaimed funds do not decrease with withdrawals
- [x] Once last reward is withdrawn bounty must terminate. 
- [x] Transaction fee label on Claim reward transaction sign modal.
- [x] Winners must always show in the respective widget. Now once reward claimed - they don't show #2702 
- [x] Once all withdrawals are made (winners are getting reduced with each withdrawal) bounty shows bounty details page shows status = Failed, No winners. This needs to show Succeeded and winners avatars in respective widget.

Bonus points:
- [x] #2703

____________
![Screenshot 2022-03-23 at 17.58.39.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/46a4b0c5-4d76-4091-aaab-b1748c09a18d)

![Screenshot 2022-03-23 at 18.00.38.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/e6ed72f0-af61-464f-9c28-0c33001b6c65)

**Comment by WRadoslaw** [comment] 2022-03-28 10:50
Issues with winners not displating after claiming reward will be fixed in #2702

**Closed** 2022-04-04 11:56 UTC
Labels: bug, scope:bounties, release:stabilisation2

**Comment by ivanturlakov** [comment] 2022-05-19 17:30
Tested on staging.

**"Unclaimed funds do not decrease with withdrawals" - The problem is still there.**
Two winners. After the first winner made a withdrawal unclaimed funds do not decrease and he is still shown the button to claim reward, after the second claiming an error occurs.
<img width="1204" alt="Снимок экрана 2022-05-19 в 19 50 34" src="https://user-images.githubusercontent.com/46903215/169359006-faab5a69-8935-406a-80e5-0c3e11b64186.png">


Further, after the second winner has claimed the reward, the bounty shows as successful/terminated
<img width="1187" alt="Снимок экрана 2022-05-19 в 19 53 49" src="https://user-images.githubusercontent.com/46903215/169359858-996e18aa-a6fd-4644-bf35-4aa746633e28.png">
Detailed
<img width="1198" alt="Снимок экрана 2022-05-19 в 19 54 19" src="https://user-images.githubusercontent.com/46903215/169360297-75ea8b23-c878-4c54-86fb-3875c6cefea3.png">



"Once last reward is withdrawn bounty must terminate" - Ok
"Transaction fee label on Claim reward transaction sign modal." - Ok
<img width="1196" alt="Снимок экрана 2022-05-19 в 19 52 17" src="https://user-images.githubusercontent.com/46903215/169361015-14e73a41-4027-4d1f-b49e-9d6917e70b40.png">


"Winners must always show in the respective widget. Now once reward claimed - they don't show" - Ok
<img width="1202" alt="Снимок экрана 2022-05-19 в 19 50 18" src="https://user-images.githubusercontent.com/46903215/169361442-afe4d2b1-e20e-4d15-8d92-225dbefd055e.png">
