### ISSUE TITLE
[USERSNAP] WG budget update Proposal not showing

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4009] opened 2023-01-04 20:35 UTC
**Taken at**: https://pioneerapp.xyz/#/proposals/preview/26
**Fields**:
- Houston, we have a problem.: WG budget update Proposal not showing
- Comment: Nothing is showing!
- Feedback: https://github.com/chrlschwb

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e84ee74e-49ec-473d-8bb1-de57d0a46141-annotated_e33ba1a8-04f3-43fe-b66b-283d01f31935.png?etag=615653000fe254ade600d21f25c9e092)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/e84ee74e-49ec-473d-8bb1-de57d0a46141-annotated_e33ba1a8-04f3-43fe-b66b-283d01f31935.png?etag=615653000fe254ade600d21f25c9e092)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1366x657
**[Open #355 in Usersnap](https://app.usersnap.com/l/feedback/3fb8883e-0881-46f8-bae6-c4c36dcd4d51?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-04 21:22
duplicate of #4011 fixed in #4012

**Closed by traumschule** 2023-01-04 21:22 UTC
Labels: bug
