### ISSUE TITLE
[USERSNAP] Display Preview not working

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4038] opened 2023-01-08 15:29 UTC
**Taken at**: https://pioneerapp.xyz/#/forum/category/40
**Fields**:
- Houston, we have a problem.: Display Preview not working
- Comment: Before creating a thread or post, the submitter should be able to view it by clicking this button

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c1c0b846-5124-4497-9ab2-6dc55b8f1a46-annotated_5c58b67e-6da6-4f96-b885-016838b745ca.png?etag=75f651c00a3245ed4f7fe4c2a4a84b69)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/c1c0b846-5124-4497-9ab2-6dc55b8f1a46-annotated_5c58b67e-6da6-4f96-b885-016838b745ca.png?etag=75f651c00a3245ed4f7fe4c2a4a84b69)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1366x657
**[Open #365 in Usersnap](https://app.usersnap.com/l/feedback/d0d4b810-12f1-4540-a9d5-66e5cd7803b0?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-08 19:13
duplicate of #3928

**Closed by traumschule** 2023-01-08 19:13 UTC
Labels: bug
