### ISSUE TITLE
[USERSNAP] fill WG lead opening proposal should include details of who applied + their description/membership details

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2338] opened 2022-02-24 14:25 UTC
**Taken at**: https://pioneer-2.vercel.app/#/proposals/current
**Fields**:
- Houston, we have a problem.: fill WG lead opening proposal should include details of who applied + their description/membership details
- Give us some details: SSIA
- SSIA
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/23d256e7-7b55-4387-af55-30ed286c92f0-annotated_1e934943-eb16-4616-be06-678252e9ee1f.png?etag=25c3530f0a32556999afcff25ce64d8c)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/23d256e7-7b55-4387-af55-30ed286c92f0-annotated_1e934943-eb16-4616-be06-678252e9ee1f.png?etag=25c3530f0a32556999afcff25ce64d8c)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1351x1020
**[Open #22 in Usersnap](https://app.usersnap.com/l/feedback/dc35841a-012e-4796-b2a4-83ffe3fc44f7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment] 2022-02-28 13:45
Closing - duplicate of #2310

**Closed by bwhm** 2022-02-28 13:45 UTC
Labels: bug
