### ISSUE TITLE
Processor crashed after pulling the latest commit

### ISSUE THREAD

**Issue by yasiryagi** [Joystream/pioneer#3488] opened 2022-08-11 10:13 UTC
I pulled the lasted yesterday and compiled, the indexer works but the processor broke. 

```
root@vmi616941:~/joystream# docker logs -f -n 100 processor
NFO: Last block: 199   : 212873 blocks behind
INFO: Starting the event queue
INFO: Processing block: 0000000200-1a099, events count: 2
ERROR: Stopping the proccessor due to errors: {} name: TypeError, message: Cannot read property 'value' of undefined, stack:                            TypeError: Cannot read property 'value' of undefined
    at NotEnoughCandidatesEvent.get params [as params] (/joystream/query-node/mappings/lib/generated/types/council.js:49:92)
    at council_NotEnoughCandidates (/joystream/query-node/mappings/lib/src/council.js:232:84)
    at MappingsLookupService.call (/joystream/node_modules/@joystream/hydra-processor/lib/executor/MappingsLookupService.js:                           80:15)
    at /joystream/node_modules/@joystream/hydra-processor/lib/executor/TransactionalExecutor.js:41:43
    at EntityManager.<anonymous> (/joystream/node_modules/typeorm/entity-manager/EntityManager.js:80:46)
    at step (/joystream/node_modules/tslib/tslib.js:144:27)
    at Object.next (/joystream/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/joystream/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR: {} name: Error, message: TypeError: Cannot read property 'value' of undefined, stack: Error: TypeError: Cannot read p                           roperty 'value' of undefined
    at MappingsProcessor.processingLoop (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js                           :75:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 1)
    at async MappingsProcessor.start (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js:25                           :9)
    at async ProcessorRunner.process (/joystream/node_modules/@joystream/hydra-processor/lib/start/ProcessorRunner.js:47:9)
    at async Run.run (/joystream/node_modules/@joystream/hydra-processor/lib/commands/run.js:27:13)
    at async Run._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/joystream/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/joystream/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
INFO: Shutting down...
INFO: Closing the database connection...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.17/lib/cli.js processor:start
Directory: /joystream/query-node
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
yarn workspace v1.22.17
yarn run v1.22.17
$ DEBUG=${DEBUG} hydra-processor run -e generated/graphql-server/.env
INFO: Starting Hydra Processor
INFO: Hydra processor lib version: 4.0.0-alpha.6
INFO: Establishing a database connection
INFO: Prometheus server is listening on port 3000. Hydra-Processor metrics are available at localhost:3000/metrics
INFO: Starting the processor
INFO: Initializing mappings executor
INFO: Waiting for the indexer head to be initialized
INFO: Hydra Indexer version: 4.0.0-alpha.0
INFO: Mappings will be executed for blocks in the range [0, Infinity], inclusively
INFO: There are already processed blocks in the database. The indexer will continue from block 200.
INFO: Last block: 199   : 212876 blocks behind
INFO: Starting the event queue
INFO: Processing block: 0000000200-1a099, events count: 2
ERROR: Stopping the proccessor due to errors: {} name: TypeError, message: Cannot read property 'value' of undefined, stack:                            TypeError: Cannot read property 'value' of undefined
    at NotEnoughCandidatesEvent.get params [as params] (/joystream/query-node/mappings/lib/generated/types/council.js:49:92)
    at council_NotEnoughCandidates (/joystream/query-node/mappings/lib/src/council.js:232:84)
    at MappingsLookupService.call (/joystream/node_modules/@joystream/hydra-processor/lib/executor/MappingsLookupService.js:                           80:15)
    at /joystream/node_modules/@joystream/hydra-processor/lib/executor/TransactionalExecutor.js:41:43
    at EntityManager.<anonymous> (/joystream/node_modules/typeorm/entity-manager/EntityManager.js:80:46)
    at step (/joystream/node_modules/tslib/tslib.js:144:27)
    at Object.next (/joystream/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/joystream/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR: {} name: Error, message: TypeError: Cannot read property 'value' of undefined, stack: Error: TypeError: Cannot read p                           roperty 'value' of undefined
    at MappingsProcessor.processingLoop (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js                           :75:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 1)
    at async MappingsProcessor.start (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js:25                           :9)
    at async ProcessorRunner.process (/joystream/node_modules/@joystream/hydra-processor/lib/start/ProcessorRunner.js:47:9)
    at async Run.run (/joystream/node_modules/@joystream/hydra-processor/lib/commands/run.js:27:13)
    at async Run._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/joystream/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/joystream/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
INFO: Shutting down...
INFO: Closing the database connection...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.17/lib/cli.js processor:start
Directory: /joystream/query-node
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
yarn workspace v1.22.17
yarn run v1.22.17
$ DEBUG=${DEBUG} hydra-processor run -e generated/graphql-server/.env
INFO: Starting Hydra Processor
INFO: Hydra processor lib version: 4.0.0-alpha.6
INFO: Establishing a database connection
INFO: Prometheus server is listening on port 3000. Hydra-Processor metrics are available at localhost:3000/metrics
INFO: Starting the processor
INFO: Initializing mappings executor
INFO: Waiting for the indexer head to be initialized
INFO: Hydra Indexer version: 4.0.0-alpha.0
INFO: Mappings will be executed for blocks in the range [0, Infinity], inclusively
INFO: There are already processed blocks in the database. The indexer will continue from block 200.
INFO: Last block: 199   : 212879 blocks behind
INFO: Starting the event queue
INFO: Processing block: 0000000200-1a099, events count: 2
ERROR: Stopping the proccessor due to errors: {} name: TypeError, message: Cannot read property 'value' of undefined, stack:                            TypeError: Cannot read property 'value' of undefined
    at NotEnoughCandidatesEvent.get params [as params] (/joystream/query-node/mappings/lib/generated/types/council.js:49:92)
    at council_NotEnoughCandidates (/joystream/query-node/mappings/lib/src/council.js:232:84)
    at MappingsLookupService.call (/joystream/node_modules/@joystream/hydra-processor/lib/executor/MappingsLookupService.js:                           80:15)
    at /joystream/node_modules/@joystream/hydra-processor/lib/executor/TransactionalExecutor.js:41:43
    at EntityManager.<anonymous> (/joystream/node_modules/typeorm/entity-manager/EntityManager.js:80:46)
    at step (/joystream/node_modules/tslib/tslib.js:144:27)
    at Object.next (/joystream/node_modules/tslib/tslib.js:125:57)
    at fulfilled (/joystream/node_modules/tslib/tslib.js:115:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
INFO: Shutting down...
ERROR: {} name: Error, message: TypeError: Cannot read property 'value' of undefined, stack: Error: TypeError: Cannot read p                           roperty 'value' of undefined
    at MappingsProcessor.processingLoop (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js                           :75:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 1)
    at async MappingsProcessor.start (/joystream/node_modules/@joystream/hydra-processor/lib/process/MappingsProcessor.js:25                           :9)
    at async ProcessorRunner.process (/joystream/node_modules/@joystream/hydra-processor/lib/start/ProcessorRunner.js:47:9)
    at async Run.run (/joystream/node_modules/@joystream/hydra-processor/lib/commands/run.js:27:13)
    at async Run._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/joystream/node_modules/@oclif/config/lib/config.js:173:24)
    at async Main.run (/joystream/node_modules/@oclif/command/lib/main.js:27:9)
    at async Main._run (/joystream/node_modules/@oclif/command/lib/command.js:43:20)
INFO: Closing the database connection...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.17/lib/cli.js processor:start
Directory: /joystream/query-node
Output:

root@vmi616941:~/joystream# ^C
root@vmi616941:~/joystream# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      3923134/docker-prox
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      3988377/systemd-res
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      461/sshd: /usr/sbin
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      3921508/docker-prox
tcp        0      0 0.0.0.0:4000            0.0.0.0:*               LISTEN      3922785/docker-prox
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      3575331/caddy
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      3922495/docker-prox
tcp6       0      0 :::80                   :::*                    LISTEN      3575331/caddy
tcp6       0      0 :::22                   :::*                    LISTEN      461/sshd: /usr/sbin
tcp6       0      0 :::443                  :::*                    LISTEN      3575331/caddy
tcp6       0      0 :::3333                 :::*                    LISTEN      3923849/node
root@vmi616941:~/joystream# docker ps
CONTAINER ID   IMAGE                                           COMMAND                  CREATED        STATUS         PORTS                                                 NAMES
7ff23a45660a   node:14                                         "docker-entrypoint.s…"   21 hours ago   Up 21 hours    0.0.0.                           0:8081->8081/tcp     graphql-server
92b68f868353   node:14                                         "docker-entrypoint.s…"   21 hours ago   Up 5 seconds                                                         processor
74e42edd3763   joystream/hydra-indexer-gateway:4.0.0-alpha.0   "docker-entrypoint.s…"   21 hours ago   Up 21 hours    0.0.0.                           0:4000->4000/tcp     hydra-indexer-gateway
a45b842f7fe9   joystream/hydra-indexer:v4.0.0-alpha.0          "docker-entrypoint.s…"   21 hours ago   Up 21 hours                                                          indexer
643950dfd6a7   redis:6.0-alpine                                "docker-entrypoint.s…"   21 hours ago   Up 21 hours    127.0.                           0.1:6379->6379/tcp   redis
be71e158d85e   postgres:12                                     "docker-entrypoint.s…"   21 hours ago   Up 21 hours    127.0.                           0.1:5432->5432/tcp   db
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202132419573087/1202783212912223) by [Unito](https://www.unito.io)

**Comment by dmtrjsg** [comment] 2022-08-11 10:37
Issue reported while testing 
- #3412

**Comment by mnaamani** [comment] 2022-08-11 11:09
Which network did this happen on ?

**Comment by zeeshanakram3** [comment] 2022-08-11 11:11
@yasiryagi can you share the commit hash?

**Comment by yasiryagi** [comment] 2022-08-11 11:23
4ee52ffad5f03fe7c429301a6231a5cd77fef392

**Comment by dmtrjsg** [comment] 2022-08-16 08:00
Could not reproduce, closing @yasiryagi shout if it happens again

**Closed by dmtrjsg** 2022-08-16 08:00 UTC
Labels: bug, carthage
