### ISSUE TITLE
[USERSNAP] Rationale in the sumbmitted proposal is broken

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3918] opened 2022-12-03 21:08 UTC
**Taken at**: https://dao.joystream.org/#/proposals/preview/75
**Fields**:
- Houston, we have a problem.: Rationale in the sumbmitted proposal is broken
- Comment: Rationale in the sumbmitted proposal is broken.
Instead of the pre-filled description I can see the long string with numbers like this 0x213423154325435432....

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1f743872-6126-4723-a49f-9b4b6920b5bf-annotated_109e554c-33e6-4dfc-a616-c5b69193f411.png?etag=3f3b9039f4e04032719a406745b1c8f4)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/1f743872-6126-4723-a49f-9b4b6920b5bf-annotated_109e554c-33e6-4dfc-a616-c5b69193f411.png?etag=3f3b9039f4e04032719a406745b1c8f4)*

**Browser**: Chrome 107 (macOS Catalina)
**Screen size**: 1920x1080
**Browser size**: 1587x856
**[Open #349 in Usersnap](https://app.usersnap.com/l/feedback/5e92eaa7-2de4-44cb-b451-5b84a0c5e9a9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2022-12-03 23:01
Reported (and not reproduced) in [#proposals](https://discord.com/channels/811216481340751934/812343755624546325/1048694787420725279). We compared QN results (hexadecimal vs utf8) for occurrences of combinations with newline or space but weren't able to make out a clear pattern. cc @bwhm @mnaamani 
`query { proposals (limit:500) {id creatorId title description details { __typename } } }`
description is parsed [here](https://github.com/Joystream/joystream/blob/master/query-node/mappings/src/proposals.ts#L323)

**Comment by dmtrjsg** [comment] 2022-12-09 11:02
@traumschule to reproduce you need non-ASCII characters. This needs to be fixed on the polkadot extension, but we don't have a way to fix it... 

Unfortunately this needs to be closed as can't fix

**Comment by dmtrjsg** [comment] 2022-12-09 11:04
there was a PR to prevent the special characters in the title.. we could probably do the same here.. Feel free to address it if you feel its repeating often.

**Comment by mkbeefcake** [comment] 2022-12-20 19:30
Hello @dmtrjsg @traumschule 
I guess I figured out the issue and simulated it. 
If CKEditor returns string with 0xc2a0 (nbsp) keycode, this issue happened. I attached here screenshots. (I can guess @dmtrjsg or @lgrex copied that string from any specific program, so the 0xc2a0 keycode is injected and then this issue happened)
I will check the code and try to solve this problem.


![Screenshot_6](https://user-images.githubusercontent.com/69617937/208750722-1b6c21e8-7362-4043-aa78-aa94f97e8e62.png)
![Screenshot_4](https://user-images.githubusercontent.com/69617937/208750571-0b54cb1c-03ac-4a87-a798-d8c27e539db6.png)
![Screenshot_5](https://user-images.githubusercontent.com/69617937/208750695-52ccedff-e1c6-4182-b60e-6ccad7d85d20.png)

**Comment by dmtrjsg** [comment] 2022-12-20 20:54
cc @thesan

**Comment by thesan** [comment] 2022-12-21 11:47
@mkbeefcake I'm not completely ruling out that CKEditor might be part of the problem but keep in mind that it happens on proposal titles too (which don't use CKE) see: #3418. nbsp is not part of ASCII so it looks like it's just another case of non-ASCII char triggering the problem.

FYI my understanding is that the problem comes from the polkadot.js lib:
> `createType('Bytes', string).toHuman()` returns the original string when string is pure ASCII but weirdly it returns the hex of the string when it contains non ASCII chars.
https://github.com/Joystream/joystream/pull/4493#issue-1494138939

**Comment by Lezek123** [comment] 2022-12-21 11:53
I agree, https://github.com/Joystream/joystream/pull/4493/files should be the correct way to solve this, there was a similar issue with member handles discovered when we were working on member migrations scripts

**Comment by thesan** [comment] 2023-01-11 12:22
Since Joystream/joystream#4493 is merged and deployed, this issue should now be completely fixed on Mainnet.

The QA can be done in #3977

**Closed by thesan** 2023-01-11 12:22 UTC
Labels: bug, high-prio, to-triage, qa-task, community-dev
