### ISSUE TITLE
[USERSNAP] -1 replies

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2885] opened 2022-04-21 20:21 UTC
**Taken at**: https://dao.joystream.org/#/forum/latest-threads
**Fields**:
- Houston, we have a problem.: -1 replies
- Comment: how is this possible?
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/694f0dc0-8f19-4366-b92c-84cdd95d838a-annotated_9f987182-beda-478e-a487-10ccca491ae3.png?etag=9954fe31972a3b2b6bc868d0bfec2f8f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/694f0dc0-8f19-4366-b92c-84cdd95d838a-annotated_9f987182-beda-478e-a487-10ccca491ae3.png?etag=9954fe31972a3b2b6bc868d0bfec2f8f)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 2868x1460
**[Open #217 in Usersnap](https://app.usersnap.com/l/feedback/3071c7ab-1fbc-4b02-8030-12944fc3de74?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by singulart** [comment] 2022-04-21 21:12
Duplicate of https://github.com/Joystream/pioneer/issues/2884

**Closed by singulart** 2022-04-21 21:12 UTC
Labels: bug
