### ISSUE TITLE
[USERSNAP] I am trying to refill Membership WG budget, after I chose membership as the WG, the screen turned white, happened several times

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4198] opened 2023-02-22 18:20 UTC
**Taken at**: https://pioneerapp.xyz/#/proposals/current
**Fields**:
- Houston, we have a problem.: I am trying to refill Membership WG budget, after I chose membership as the WG, the screen turned white, happened several times
- Comment: I expect it to let me choose which WG and proceed with the proposal refill.
- Feedback: jen4ph

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ff40816c-a030-4e1b-9e84-5db2b8c7c1bb-annotated_8e4958af-06aa-4c6d-97e8-051e096ad5d6.png?etag=30c2cdad8aec83e5ca0ea35757a2dace)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/ff40816c-a030-4e1b-9e84-5db2b8c7c1bb-annotated_8e4958af-06aa-4c6d-97e8-051e096ad5d6.png?etag=30c2cdad8aec83e5ca0ea35757a2dace)*

**Browser**: Chrome 103 (macOS Sierra)
**Screen size**: 1440x900
**Browser size**: 1920x1094
**[Open #393 in Usersnap](https://app.usersnap.com/l/feedback/3b87afbc-dde7-4722-9ba8-4f5ff43b4716?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment] 2023-02-23 02:29
It looks like this is caused by the current budget of the membership WG being `-1`

**Comment by mochet** [comment] 2023-02-27 10:01
This issue breaks the creation of proposals but a workaround can be used to rectify this:
`membershipWorkingGroup.fundWorkingGroupBudget` - if a user submits this extrinsic with some amount of tokens it will push the balance to be `0` again which will stop pioneer from crashing

**Comment by mochet** [comment] 2023-10-19 12:56
This has been fixed for a while so closing (I'm the membership lead and have used this proposal type successfully)

**Closed by mochet** 2023-10-19 12:56 UTC
Labels: bug, community-dev, upstream:query node
