### ISSUE TITLE
[USERSNAP] `Time left` is wrong for gracing proposal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3006] opened 2022-05-09 20:12 UTC
**Taken at**: https://dao.joystream.org/#/proposals/preview/161
**Fields**:
- Houston, we have a problem.: `Time left` is wrong for gracing proposal
- Comment: Proposal 161 executes in 697,500 but `Time left` counts upwards (26min at block 675375).
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/72693aa6-c6e1-4e69-b7f8-542f466fc939-annotated_7b119b1a-153d-4a06-8056-1e4724e7c181.png?etag=48632225046c3a6057b517451593dbf7)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/72693aa6-c6e1-4e69-b7f8-542f466fc939-annotated_7b119b1a-153d-4a06-8056-1e4724e7c181.png?etag=48632225046c3a6057b517451593dbf7)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1190x1143
**[Open #246 in Usersnap](https://app.usersnap.com/l/feedback/33545f65-b539-42f2-9201-a6fc87ff8de6?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2022-05-09 20:15
duplicate of https://github.com/Joystream/pioneer/issues/3001

**Comment by traumschule** [comment] 2022-05-12 08:34
fixed in #3003

**Closed** 2022-06-06 12:58 UTC
Labels: bug
