### ISSUE TITLE
[USERSNAP] Forum: After post creation, prompt given to close modal

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4021] opened 2023-01-06 03:00 UTC
**Taken at**: https://pioneerapp.xyz/#/forum/thread/4
**Fields**:
- Houston, we have a problem.: Forum: After post creation, prompt given to close modal
- Comment: The thread/post was made successfully, but clicking &#34;View my thread&#34; for some unknown reason triggers this prompt.
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/70265ea8-2ce5-41ae-9b82-9abecaa23114-annotated_7d31bb60-6802-49c4-95f8-ed67b7e95be1.png?etag=5953993887fb9ce272e720f94656b985)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/70265ea8-2ce5-41ae-9b82-9abecaa23114-annotated_7d31bb60-6802-49c4-95f8-ed67b7e95be1.png?etag=5953993887fb9ce272e720f94656b985)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 1392x665
**[Open #360 in Usersnap](https://app.usersnap.com/l/feedback/4e156e26-14c1-45f0-a608-13ea6bb52309?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-06 07:29
duplicate of #3899

**Closed by traumschule** 2023-01-06 07:29 UTC
Labels: bug
