### ISSUE TITLE
[USERSNAP] Rationale does not show information

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4002] opened 2023-01-03 13:07 UTC
**Taken at**: https://pioneerapp.xyz/#/proposals/preview/12
**Fields**:
- Houston, we have a problem.: Rationale does not show information
- Comment: For example, in this proposal the information is displayed correctly - https://pioneerapp.xyz/#/proposals/preview/11
- Feedback: adovrn

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/88a89790-fe88-46f0-a968-27ae14708220-annotated_0e2551c5-cdde-4360-b545-d06fadcf29e1.png?etag=2404452b1ad4a71210f8ba313762cb5f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/88a89790-fe88-46f0-a968-27ae14708220-annotated_0e2551c5-cdde-4360-b545-d06fadcf29e1.png?etag=2404452b1ad4a71210f8ba313762cb5f)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1536x864
**Browser size**: 1536x792
**[Open #351 in Usersnap](https://app.usersnap.com/l/feedback/9916bdf0-db01-4e4e-b3c9-f053c3b89682?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-05 04:15
duplicate of #3918

**Closed by traumschule** 2023-01-05 04:15 UTC
Labels: bug
