### ISSUE TITLE
Update WG budget proposal details page shows blank

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3994] opened 2022-12-22 12:24 UTC
Env: https://dao-git-ephesus-joystream.vercel.app/#/proposals/current

Proposal: https://dao-git-ephesus-joystream.vercel.app/#/proposals/preview/12

![Screenshot 2022-12-22 at 16.23.27.png](https://images.zenhubusercontent.com/6197874e1913711bf1f6ad31/211e3576-eef0-4bed-a7a0-195034a6a339)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202078489349362/1203601281548392) by [Unito](https://www.unito.io)

**Comment by traumschule** [comment] 2022-12-22 18:11
I believe there is a problem when no lead is set. The WG should be hidden from the selection.

![ephesus-wg-select](https://user-images.githubusercontent.com/31551045/209198792-3935ba8b-a90f-4ad8-a7ba-a2afe1c31917.png)

![ephesus-leads](https://user-images.githubusercontent.com/31551045/209198070-76386d7e-eed2-4aee-a926-f4f6b2a7457a.png)

However the proposal shows all details: https://dao-git-ephesus-joystream.vercel.app/#/proposals/preview/5
It is rejected as expected since there's no council.

![proposal5](https://user-images.githubusercontent.com/31551045/209198467-db92aead-d5c5-4d6e-b9cb-5b86370ee3e0.png)

**Comment by thesan** [comment] 2022-12-22 18:16
So this comes from the QN returning the update amount as a `number`. The problem is that the amount is `50000000000000000` which is (one digit) greater than `Number.MAX_SAFE_INTEGER` as a result the `bn.js` throws an error.

Try this on https://atlas-next.joystream.org/query-node/server/graphql:
```gql
query {
  proposals (where: { details_json: { isTypeOf_eq: "UpdateWorkingGroupBudgetProposalDetails" } }) {
    details {
      ...on UpdateWorkingGroupBudgetProposalDetails { amount }
    }
  }
}
```

It's potentially a wide spread issue because although Pioneer expects strings since [this change](https://github.com/Joystream/pioneer/pull/3335/files#diff-b9ca97457feb4162955676ae3378c8338e2be767cd9b7155e018f0c49ee58a6e) all the `Float` values from [`@/common/api/schemas/schema.graphql`](https://github.com/Joystream/pioneer/blob/dev/packages/ui/src/common/api/schemas/schema.graphql) are returned from the QN as `number`. For stuff like block numbers it's fine (although `Int` would be more appropriate) but for JOY amount this often might trigger exceptions in `bn.js`. This is actually the bug that @traumschule reported here: https://github.com/Joystream/pioneer/issues/2327#issuecomment-1336443690.

A quick fix here would be to just cast the amount to a `string` and then to a `BN`. However it also means a small precision loss.

I don't think this can be fixed long term on the client. @zeeshanakram3, @Lezek123 can you think of an easy fix on the QN for this ?

**Comment by thesan** [comment] 2022-12-23 15:22
Until #3995 is merged this env can be used to pass the crashing proposals: https://dao-git-fix-proposal-view-crash-joystream.vercel.app

E.g: https://dao-git-fix-proposal-view-crash-joystream.vercel.app/#/proposals/preview/12?network-config=https://atlas-next.joystream.org/network/config.json

**Closed** 2023-01-06 16:05 UTC
Labels: bug, ephesus
