### ISSUE TITLE
Claim vested $JOY

### ISSUE THREAD

**Issue by bedeho** [Joystream/pioneer#2959] opened 2022-05-03 17:23 UTC
## Context
On mainnet, $JOY will be encumbered by a vesting schedule, and giving users a simple way to claim such $JOY, and seeing what the vesting vs. vested balance for individual accounts.
:information_source:  Here's technical details https://polkadot.js.org/docs/substrate/extrinsics/#vesting

## Design

[LINK TO FIGMA > ](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10535%3A402088)

## Scope

Individual Locks on account level:

- [ ] Staring block
- [ ] Ending block
- [ ] Original Vesting
- [ ] Unlocked per block
- [ ] Locked
- [ ] Claimable

Widgets for compound info on all locks across accounts:

- [ ] Total Vesting
- [ ] Total Locked
- [ ] Total Claimable
- [ ] Claim CTA
- [ ] Ability to claim full amount  only (user cannot specify how much to claim from single account/ Claiming is possible from one account at a time)

☝️  @ QA

<img width="339" alt="Screenshot 2022-08-10 at 15 50 33" src="https://user-images.githubusercontent.com/93924525/183934274-d881102f-8016-4124-b6f4-379403a48f75.png">

Test with multiple accounts for single memebrship and multiple locks per single account

**Comment by bedeho** [comment] 2022-06-17 08:21
> Add a new tab "Vested Tokens"

This description does not spell it out entirely, but what entity does a row here correspond to? its not tokens or a token, its an account, vesting occurs per account. The natural place of such information is the account table, why a new table?

**Comment by bedeho** [comment] 2022-06-20 18:02
I don't think I understand this, feel free to supply a low-fi sketch or something.

**Comment by dmtrjsg** [comment] 2022-06-23 13:00
Issue description re-written after confirmed with Bedeho.

**Comment by bedeho** [comment] 2022-07-01 09:53
1. I think so yes, but even if you could claim them to some other account, this can be done in a second transfer later, so lets not overcomplicate the design with this variation even if possible.
2. What do you mean by unilateral, do you mean identical? if so then no, and there will be future stakeholders that may be subject to new vesting schedules.
3. This question was a  bit unclear, but on mainnet launch, each account will have exactly one vesting allocation. In the future, its unclear whether we will do more vesting allocations, but they would almost certainly be on fresh accounts, so the vast majority of accounts with vesting will have 1 allocation.

**Comment by dmtrjsg** [comment] 2022-07-01 09:59
@Adam based on the above:
1. I suggest to include “cliff duration” and “unlocked after cliff %” as explicit details to the vesting lock card. 
2. Since the allocation rules are different, the tooltip with the diagram can benefit from additional copy “This chart is only for illustration purposes, please refer to the vesting lock details for actual info).

**Comment by bedeho** [comment] 2022-07-01 10:55
I have to stress that you really need to speak to @thesan or someone to make sure you are designing in accordance with the low level properties of the vesting mechanism being used, this is not like $CRT vesting. I am not sure how or whether cliffs exist as a concept directly, this must be fully verified. Has this all been checked out?

**Comment by dmtrjsg** [comment] 2022-07-01 12:27
That's a fair point, and we did not have a chance to drive this by Theo just yet. Duly noted.

cc @thesan

**Comment by dmtrjsg** [comment] 2022-07-04 16:00
Mokhtar kindly pointed me to the pallet documentation and based on my review, we only have the 
- starting block  
- vesting per each block
- min vested transfer [not sure if this is this to allocate or to recover tokens ❓]

[Link to documentation >](https://docs.rs/pallet-vesting/latest/pallet_vesting/trait.Config.html)
(see img)
<img width="1082" alt="Screenshot 2022-07-04 at 16 56 41" src="https://user-images.githubusercontent.com/93924525/177188510-f5d37f70-f10e-43fb-aa8c-0283f38e5996.png">

**Comment by dmtrjsg** [comment] 2022-07-20 13:24
Outstanding points to clarify:

* Starting block can be in the future (from the point of adding the lock, so this delay is representing a cliff)
* Is vesting schedule linear or defined by custom function?
 * Whether unlocked funds can be transferred to any account at any moment (without any minimum accruals) and does not require the act of “claiming” the unlocked funds
 
 preview of vesting lock component: 
 
<img width="707" alt="Screenshot 2022-07-20 at 14 23 49" src="https://user-images.githubusercontent.com/93924525/179993288-e2b3daf2-f16d-4a20-ba71-bc8e114f274f.png">

LInk to Figma [full designs](https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10216%3A404932) (draft awaits feedback to iterate)

@ignazio-bovo one for your eyes buddy 👀

**Comment by ignazio-bovo** [comment] 2022-07-21 07:27
* Starting block can be in the future (from the point of adding the lock, so this delay is representing a cliff) :heavy_check_mark: 
 Basically substrate uses a `locked_at` method (function) for accounting the amount that is locked at a particular `block` (and cannot be recovered yet). The formula is : `total_locked_amount - rate * (block - starting_block)` https://github.com/paritytech/substrate/blob/88abf20f01c73cd98515d95e257a7c6b885b8373/frame/vesting/src/vesting_info.rs#L77
 * Is vesting schedule linear or defined by custom function?
 Linear, in any case, because of the above accounting methodology
 * Whether unlocked funds can be transferred to any account at any moment (without any minimum accruals) and does not require the act of “claiming” the unlocked funds
 Accrued balance amount can be _vested_ by invoking the `vest` extrinsic. This effectively reduces/removes the locked amount on the
`free_balance` of an account (this is the amount that can be transferred, provided that there are no other locks for the account). So basically if an account has only one vesting schedule and no other locks and the user would like to accrue some vested amount in order to transfer it somewhere else he will:
1. invoke `vest` which reduces the locked amount behind the scene https://github.com/paritytech/substrate/blob/88abf20f01c73cd98515d95e257a7c6b885b8373/frame/vesting/src/lib.rs#L603
2. transfer the desired amount, having higher availability of `free_balance`

**Comment by dmtrjsg** [comment] 2022-07-21 14:35
@ignazio-bovo thanks a mil for your curation! re point 3 

Cliff ✅ 
Liner vesting schedule ✅ 

On the third question a few additional questions:

Does this mean in the UI terms that we shall rather show “Unlocked” balance separate to “Transferable” and “Locked in vesting schedule” balances to the user and they would need to “Vest”   the unlocked amount, (or aka “Recover" as per [this mockup](https://github.com/Joystream/pioneer/issues/2959#issuecomment-1190284160)), resulting in increase of Transferable balance and Decrease (to full amount) of Unlocked balance?

Is vesting only allowed to the account where lock is imposed? Or one can specify the destination account in the extrinsic?

**Comment by ignazio-bovo** [comment] 2022-07-21 14:43
>Does this mean in the UI terms that we shall rather show “Unlocked” balance separate to “Transferable” and “Locked in vesting schedule” balances to the user and they would need to “Vest” the unlocked amount, (or aka “Recover" as per https://github.com/Joystream/pioneer/issues/2959#issuecomment-1190284160), resulting in increase of Transferable balance and Decrease (to full amount) of Unlocked balance?

I would recommend the following words (so that re-use the same terminology used in the runtime implementation):
- Vested instead of Unlocked
- Unvested instead of Locked In
- Vest instead of Recover (but I also don't mind Recover either)

> Is vesting only allowed to the account where lock is imposed? Or one can specify the destination account in the extrinsic?

Yes locks are restriction imposed on your free balance.
When a vesting schedule is added to your account more or less the following happens:
- `free_balance += total_amount`
- when you transfer amount `x` at `block` the following check is performed `free_balance - vesting_schedule.locked_at(block) >= x`

**Comment by toiletgranny** [comment] 2022-07-28 11:53
@dmtrjsg Below is the link tothe updated My Profile tab designs with added vesting locks information, based on our earlier discussion. I made one simple change in spite of our prior agreement, and that is to refer to the act of unlocking your vested coins as _Claiming_, instead of _Vesting_. So, for example, the button bringing up the dialog that allows you to unlock your vested tokens is called "Claim" in the UI, not "Vest". I did this having quickly researched and confirmed that this is indeed how other services refer to this type of action. Hope that's okay with you, let me know if you think otherwise. 

https://www.figma.com/file/GlgN8uBRtvtMJtiOsdtDF7/Pioneer-Design?node-id=10535%3A402088

---

To whoever will be the engineer implementing this, I left a few comments in Figma here and there explaining "fallback UI behavior" for different scenarios. Please, be sure to check them out by enabling comments visibility in Figma (Shift + C).
![CleanShot 2022-07-28 at 13 45 59](https://user-images.githubusercontent.com/35307309/181497459-0f916133-f921-4283-a3bc-3f69a4eb1c23.png)

**Comment by dmtrjsg** [comment] 2022-07-28 12:00
@WRadoslaw  ready to go buddy 😎

**Comment by dmtrjsg** [comment] 2022-07-28 12:17
+ AC if there is no vesting locks, we don’t show widget for vesting locks on top of the page.

**Comment by dmtrjsg** [comment] 2022-07-29 09:05
<img width="679" alt="Screenshot 2022-07-29 at 10 05 40" src="https://user-images.githubusercontent.com/93924525/181725133-86327536-7f96-4b6d-b79b-f2506258d974.png">

**Closed** 2022-08-29 15:05 UTC
Labels: qa-task, community-dev, carthage
