### ISSUE TITLE
Search Member by ID

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3369] opened 2022-07-19 09:32 UTC
## Context

Follow up use case originating from this comment: 
- https://github.com/Joystream/pioneer/issues/2657#issuecomment-1173671702

## Scope

- [ ] Enable searching member by ID

**Comment by traumschule** [comment] 2022-10-20 17:51
duplicate of #3390 #2032 (implemented)

![member search](https://user-images.githubusercontent.com/31551045/197021700-d65abd16-0244-4ad0-9d95-e305e0b1f676.png)

**Closed by traumschule** 2022-10-20 17:51 UTC
Labels: enhancement, scope:members, community-dev, SP:3
