### ISSUE TITLE
[USERSNAP] DISPLAY PREVIEW button is not working

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4058] opened 2023-01-11 07:53 UTC
**Taken at**: https://pioneerapp.xyz/#/forum/category/47
**Fields**:
- Houston, we have a problem.: DISPLAY PREVIEW button is not working
- Comment: I want to see how my post will look like before signing the transaction. But this button is not working.
- Feedback: Jen4ph#5477

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/63cbccf6-8e89-4abf-831f-3de27eaad208-annotated_26383ddc-d74b-42d6-8b3b-6acc3db52437.png?etag=52708c1d4a2f30a341ccd50c7e673793)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/63cbccf6-8e89-4abf-831f-3de27eaad208-annotated_26383ddc-d74b-42d6-8b3b-6acc3db52437.png?etag=52708c1d4a2f30a341ccd50c7e673793)*

**Browser**: Chrome 103 (macOS Sierra)
**Screen size**: 1440x900
**Browser size**: 1440x722
**[Open #374 in Usersnap](https://app.usersnap.com/l/feedback/ad3538eb-b4c2-4ea1-a877-496d70e01de7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-11 07:58
duplicate of #3928

**Closed by traumschule** 2023-01-11 07:58 UTC
Labels: bug
