### ISSUE TITLE
[USERSNAP] Proposal not loading

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4013] opened 2023-01-05 02:35 UTC
**Taken at**: https://pioneerapp.xyz/#/proposals/preview/26
**Fields**:
- Houston, we have a problem.: Proposal not loading
- Comment: https://pioneerapp.xyz/#/proposals/preview/26
blank page failure

react-dom.production.min.js:216 Error: Assertion failed
    at i (bn.js:6:21)
    at r._initNumber (bn.js:128:7)
    at r._init (bn.js:82:19)
    at new r (bn.js:39:12)
    at Object.UpdateWorkingGroupBudgetProposalDetails (ProposalDetails.ts:222:11)
    at n.asProposalDetails (ProposalDetails.ts:352:31)
    at n.asProposalWithDetails (ProposalWithDetails.ts:58:12)
    at n.useProposal (useProposal.ts:16:39)
    at n.ProposalPreview (ProposalPreview.tsx:45:35)
    at ro (react-dom.production.min.js:157:137)
dd @ react-dom.production.min.js:216
module.js:62 Uncaught Error: Assertion failed
    at i (bn.js:6:21)
    at r._initNumber (bn.js:128:7)
    at r._init (bn.js:82:19)
    at new r (bn.js:39:12)
    at Object.UpdateWorkingGroupBudgetProposalDetails (ProposalDetails.ts:222:11)
    at n.asProposalDetails (ProposalDetails.ts:352:31)
    at n.asProposalWithDetails (ProposalWithDetails.ts:58:12)
    at n.useProposal (useProposal.ts:16:39)
    at n.ProposalPreview (ProposalPreview.tsx:45:35)
    at ro (react-dom.production.min.js:157:137)
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4d15ca38-0198-41f0-90a5-f3dbb55c3ea6-annotated_70763c83-baa5-43c0-9909-2062506043b4.png?etag=13579d737b5053bb284a69b630c0658b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/4d15ca38-0198-41f0-90a5-f3dbb55c3ea6-annotated_70763c83-baa5-43c0-9909-2062506043b4.png?etag=13579d737b5053bb284a69b630c0658b)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 1440x900
**Browser size**: 873x738
**[Open #357 in Usersnap](https://app.usersnap.com/l/feedback/4c0a91b3-d1bd-40a5-a154-707b54a4c7c5?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by mochet** [comment] 2023-01-05 02:36
duplicate of #4011

**Closed by mochet** 2023-01-05 02:36 UTC
Labels: bug
