### ISSUE TITLE
[USERSNAP] After manually setting the whitelist, I can't post with any membership

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2494] opened 2022-03-07 23:16 UTC
**Taken at**: https://pioneer-2.vercel.app/#/proposals/preview/114
**Fields**:
- Houston, we have a problem.: After manually setting the whitelist, I can&#39;t post with any membership
- Give us some details: Including a CM
- -
- Discrod Handle: bwhm

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3a654368-7b7b-4593-96c5-41e5d292db87-annotated_613ec5f7-0a72-4634-823b-36cd26a24549.png?etag=31c81ed302a330e4a328e39a48e35c64)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/3a654368-7b7b-4593-96c5-41e5d292db87-annotated_613ec5f7-0a72-4634-823b-36cd26a24549.png?etag=31c81ed302a330e4a328e39a48e35c64)*

**Browser**: Firefox 97 (macOS Catalina)
**Screen size**: 2859x1608
**Browser size**: 2144x1117
**Labels**: bug-non-critical
**[Open #102 in Usersnap](https://app.usersnap.com/l/feedback/3b71a968-5c52-4870-bb0d-d17bac9988c9?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment] 2022-03-08 12:08
duplicate of #2481

**Closed by bwhm** 2022-03-08 12:08 UTC
Labels: bug
