### ISSUE TITLE
[USERSNAP] Problem in creating new thread

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2863] opened 2022-04-15 16:47 UTC
**Taken at**: https://dao.joystream.org/#/forum/category/23
**Fields**:
- Houston, we have a problem.: Problem in creating new thread
- Comment: When i try to create a new thread and paste a big text, the form roll down under the screen and i cant push the &#34;Next step&#34; button
- Feedback: MarikJud0#1899 ( discord)

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/bdcd0037-e0f8-43e6-b768-058eb8205f11-annotated_7a1fb2b2-24a3-47ad-b64e-be70685222a5.png?etag=5e4311c105b8c292153ee433e8fbb0dd)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/bdcd0037-e0f8-43e6-b768-058eb8205f11-annotated_7a1fb2b2-24a3-47ad-b64e-be70685222a5.png?etag=5e4311c105b8c292153ee433e8fbb0dd)*

**Browser**: Chrome 100 (Windows 10)
**Screen size**: 1366x768
**Browser size**: 1366x657
**[Open #210 in Usersnap](https://app.usersnap.com/l/feedback/bcf20b97-3239-4a2d-9708-4748776349ec?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by singulart** [comment] 2022-04-21 21:17
Duplicate of https://github.com/Joystream/pioneer/issues/2864

**Closed by singulart** 2022-04-21 21:17 UTC
Labels: bug, scope:forum
