### ISSUE TITLE
Proposal Activities Not Updating

### ISSUE THREAD

**Issue by Codefikeyz** [Joystream/pioneer#4686] opened 2023-12-08 13:47 UTC
**Taken at** https://pioneerapp.xyz/#/proposals/current

- Proposal activities stopped updating 6 months ago

![Screenshot_71](https://github.com/Joystream/pioneer/assets/123887455/816a45b1-1191-40e8-972b-55982521836d)

**Comment by mochet** [comment] 2023-12-21 10:48
duplicate of https://github.com/Joystream/pioneer/issues/4673

**Closed by mochet** 2023-12-21 10:48 UTC
Labels: bug
