### ISSUE TITLE
[USERSNAP] Forum post reply not showing

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4022] opened 2023-01-06 04:01 UTC
**Taken at**: https://pioneerapp.xyz/#/forum/thread/3
**Fields**:
- Houston, we have a problem.: Forum post reply not showing
- Comment: There should be the post above &#34;replies to abramaria&#34;

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8df19d08-9047-4d43-aec0-45621d618aed-annotated_7469ba9f-fb0c-4cc8-a8dd-c477cd077fb6.png?etag=26c37bd52a7d763df01a6ab9dd85f5bc)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/8df19d08-9047-4d43-aec0-45621d618aed-annotated_7469ba9f-fb0c-4cc8-a8dd-c477cd077fb6.png?etag=26c37bd52a7d763df01a6ab9dd85f5bc)*

**Browser**: Chrome 108 (Windows 10)
**Screen size**: 1600x900
**Browser size**: 1366x657
**[Open #361 in Usersnap](https://app.usersnap.com/l/feedback/fa2ac0d5-dd8a-4799-a54b-983e2f309fcc?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-06 07:25
duplicate of #3967

**Closed by traumschule** 2023-01-06 07:25 UTC
Labels: bug

**Comment by mkbeefcake** [comment] 2023-01-06 09:50
https://pioneer-2-git-mainnet-joystream.vercel.app/#/forum/thread/34
wss://34.230.5.182.nip.io/ws-rpc

I have tried it with latest dev branch with testnet, but it looks like working well...

**Comment by mkbeefcake** [comment] 2023-01-06 11:30
I created the pull request for this issue
