### ISSUE TITLE
[USERSNAP] Forum post text overflowing container

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4048] opened 2023-01-09 22:24 UTC
**Taken at**: https://pioneerapp.xyz/#/forum/thread/17
**Fields**:
- Houston, we have a problem.: Forum post text overflowing container
- Comment: All the text should be contained inside the white card

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/702cabfe-b3a6-4732-8829-f05215a83e78-annotated_83cc0764-6f92-4d8b-bdc8-84f1de497ef6.png?etag=a04730664b7254246be4c3c584f7b175)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/702cabfe-b3a6-4732-8829-f05215a83e78-annotated_83cc0764-6f92-4d8b-bdc8-84f1de497ef6.png?etag=a04730664b7254246be4c3c584f7b175)*

**Browser**: Chrome 108 (macOS Catalina)
**Screen size**: 1728x1117
**Browser size**: 1404x971
**[Open #372 in Usersnap](https://app.usersnap.com/l/feedback/68042f9b-19ef-4baa-8372-19912f1e32e7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2023-01-09 22:42
One solution is to truncate or force-break links. What is better?

**Comment by chrlschwb** [comment] 2023-01-11 14:40
sometimes the text is inside the card and sometimes it's overflowing. What's the cause?

**Comment by traumschule** [comment] 2023-01-11 20:47
look out for `position: absolute` within `.markdown-preview ol`

**Comment by IlyaSmiyukha** [comment] 2023-03-29 09:49
resolved with this PR https://github.com/Joystream/pioneer/pull/4296
#4256 duplicated issue

**Comment by ivanturlakov** [comment] 2023-04-02 12:45
✅ Tested on https://dao-git-dev-joystream.vercel.app/#/forum/thread/17
Mainnet

<img width="1206" alt="Screenshot 2023-04-02 at 15 43 21" src="https://user-images.githubusercontent.com/46903215/229353526-f11ebae7-b77e-48f3-a0ad-354b124cf554.png">

**Closed** 2023-04-03 04:20 UTC
Labels: bug, community-dev, qa-tested-ready-for-prod, SP:1, release:1.3.2
