### ISSUE TITLE
[USERSNAP] Links don't wrap

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#4256] opened 2023-03-23 05:26 UTC
**Taken at**: https://pioneerapp.xyz/#/forum/thread/308
**Fields**:
- Houston, we have a problem.: Links don&#39;t wrap
- Comment: links should wrap, just like other text.

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/666a62c8-e2de-4d94-a47b-ccd9091375ce-annotated_c7a12db1-16fa-4204-9805-be5feafe8599.png?etag=88e8999654f3a450f843cfed2002d892)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/666a62c8-e2de-4d94-a47b-ccd9091375ce-annotated_c7a12db1-16fa-4204-9805-be5feafe8599.png?etag=88e8999654f3a450f843cfed2002d892)*

**Browser**: Chrome 111 (Windows 10)
**Screen size**: 3840x2160
**Browser size**: 1366x657
**[Open #405 in Usersnap](https://app.usersnap.com/l/feedback/5e7e15ed-5e6a-44e9-8917-428cd9bb99e7?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by thesan** [comment] 2023-03-30 10:37
Duplicate of #4048

**Closed by thesan** 2023-03-30 10:37 UTC
Labels: bug, duplicate, community-dev
