### ISSUE TITLE
[USERSNAP] Can't see candidate that successfully applied

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2343] opened 2022-02-24 16:42 UTC
**Taken at**: https://pioneer-2.vercel.app/#/election
**Fields**:
- Houston, we have a problem.: Can&#39;t see candidate that successfully applied
- Give us some details: SSIA
- SSIA
- Discrod Handle: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2de33a02-d2d6-4a0d-b8dd-36fefaad4706-annotated_45a49dac-0332-45b5-939a-39f0009cd7b8.png?etag=bd2fd2c655b73266b6bfe28123225d19)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/2de33a02-d2d6-4a0d-b8dd-36fefaad4706-annotated_45a49dac-0332-45b5-939a-39f0009cd7b8.png?etag=bd2fd2c655b73266b6bfe28123225d19)*

**Browser**: Chrome 98 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1351x1116
**[Open #24 in Usersnap](https://app.usersnap.com/l/feedback/03958cab-29e6-425e-81a0-492a0dd31ffa?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by bwhm** [comment] 2022-02-28 13:37
Closing, as duplicate of #2277

**Closed by bwhm** 2022-02-28 13:37 UTC
Labels: bug
