### ISSUE TITLE
[USERSNAP] Past Councils > Term ID is not human readable

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#3226] opened 2022-06-12 11:19 UTC
## Scope

- [ ] Show election_round_cycle instead of election_id

<img width="230" alt="Screenshot 2022-06-17 at 18 57 04" src="https://user-images.githubusercontent.com/93924525/174293741-798d7bae-c5c4-4fe5-b6d1-8084adc5b679.png">

____________

**Taken at**: https://dao.joystream.org/#/council/past-councils
**Fields**:
- Houston, we have a problem.: Past Councils &gt; Term ID is not human readable
- Comment: SSIA
Once it goes past 9 it goes to binary or something.
- Feedback: tomato#9464

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6c0634a7-a83d-4544-a8eb-7005ab68006d-annotated_bcb680c6-698a-4418-a367-8919590fe2da.png?etag=6441653c06c0593a3cb50943f1a5563f)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/6c0634a7-a83d-4544-a8eb-7005ab68006d-annotated_bcb680c6-698a-4418-a367-8919590fe2da.png?etag=6441653c06c0593a3cb50943f1a5563f)*

**Browser**: Chrome 102 (Windows 10)
**Screen size**: 3440x1440
**Browser size**: 1556x1206
**[Open #277 in Usersnap](https://app.usersnap.com/l/feedback/0c21bc70-238e-4ac3-a6f8-b1c19adece4f?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by traumschule** [comment] 2022-12-06 18:15
duplicate of #3179

**Closed by traumschule** 2022-12-06 18:15 UTC
Labels: bug, scope:council, community-dev, bounty-backlog, SP:2
